In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [57]:
df=pd.read_csv(r"C:\projects\job_market_analysis\data\indeed_analyst_jobs_august_2024.csv")
df_clean = df.copy()
df_clean

,job_title,employer,rating,location,salary_raw,salary_annual,job_type,work_mode,raw_job_description,job_description,industry,city,state
0,Data Analyst,NYU Langone Health,4.3,"240 E 38 St, New York, NY 10016","$62,400 - $65,000 a year",63700.0,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",NYU Grossman School of Medicine is one of the ...,Healthcare,New York,NY
1,Data Analyst 1,"Human Rights, Division of",NaN,"Albany, NY 12220","$65,001 - $82,656 a year",73828.5,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",Minimum Qualifications Bachelor’s degree in da...,NaN,Albany,NY
2,Claims Data Analyst,Healthfirst,3.3,Remote,"$59,800 - $97,815 a year",78807.5,Full-time,Remote,"<div class=""jobsearch-JobComponent-description...",This position is Remote Develop and maintain n...,NaN,NaN,NaN
3,HRIS Data Analyst,Hershey Entertainment & Resorts Company,3.8,"27 W Chocolate Ave, Hershey, PA 17033",NaN,NaN,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",Hershey Entertainment & Resorts Company (HE&R)...,NaN,Hershey,PA
4,Artist Engagement Data Analyst - USDS,TikTok,3.4,"Los Angeles, CA","$82,227 - $168,355 a year",125291.0,NaN,Hybrid work,"<div class=""jobsearch-JobComponent-description...",Responsibilities About TikTok U.S. Data Securi...,Internet & Web Services,Los Angeles,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1448,ASSOCIATE GOVERNMENTAL PROGRAM ANALYST,Saginaw County Community Mental Health Authority,4.0,"Sacramento County, CA","$5,855 - $7,327 a month",79092.0,Full-time,Remote,"<div class=""jobsearch-JobComponent-description...",Why Join DHCS? The Department of Health Care S...,Hospitals & Health Clinics,Sacramento County,CA
1449,Business Systems/Data Analyst III,The University of Chicago,3.8,"3301 College Ave, Fort Lauderdale, FL 33314",NaN,NaN,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",Business Systems/Data Analyst III - 991491 Job...,Education,Fort Lauderdale,FL
1450,"Analyst, Health Informatics Principal",California State University,3.7,"Bloomington, MN",NaN,NaN,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",JOB DESCRIPTION HealthPartners is hiring a Hea...,Education,Bloomington,MN
1451,Hispanic Serving Institution (HSI) Data Analyst,Clario,4.0,"Redlands, CA 92374","$66,560 - $72,500 a year",69530.0,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",POSITION CODE: 6952 DEPARTMENT/ADMINISTRATION:...,Software Development,Redlands,CA
1452,Business Analyst,Coterie Insurance,3.2,"Charlotte, NC",NaN,NaN,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",Job Description: Role Summary: The Business An...,Insurance,Charlotte,NC

In [48]:
df_clean.drop('raw_job_description',axis=1)

,job_title,employer,rating,location,salary_raw,salary_annual,job_type,work_mode,job_description,industry,city,state
0,Data Analyst,NYU Langone Health,4.3,"240 E 38 St, New York, NY 10016","$62,400 - $65,000 a year",63700.0,Full-time,In-office,NYU Grossman School of Medicine is one of the ...,Healthcare,New York,NY
1,Data Analyst 1,"Human Rights, Division of",NaN,"Albany, NY 12220","$65,001 - $82,656 a year",73828.5,Full-time,In-office,Minimum Qualifications Bachelor’s degree in da...,NaN,Albany,NY
2,Claims Data Analyst,Healthfirst,3.3,Remote,"$59,800 - $97,815 a year",78807.5,Full-time,Remote,This position is Remote Develop and maintain n...,NaN,NaN,NaN
3,HRIS Data Analyst,Hershey Entertainment & Resorts Company,3.8,"27 W Chocolate Ave, Hershey, PA 17033",NaN,NaN,Full-time,In-office,Hershey Entertainment & Resorts Company (HE&R)...,NaN,Hershey,PA
4,Artist Engagement Data Analyst - USDS,TikTok,3.4,"Los Angeles, CA","$82,227 - $168,355 a year",125291.0,NaN,Hybrid work,Responsibilities About TikTok U.S. Data Securi...,Internet & Web Services,Los Angeles,CA
...,...,...,...,...,...,...,...,...,...,...,...,...
1448,ASSOCIATE GOVERNMENTAL PROGRAM ANALYST,Saginaw County Community Mental Health Authority,4.0,"Sacramento County, CA","$5,855 - $7,327 a month",79092.0,Full-time,Remote,Why Join DHCS? The Department of Health Care S...,Hospitals & Health Clinics,Sacramento County,CA
1449,Business Systems/Data Analyst III,The University of Chicago,3.8,"3301 College Ave, Fort Lauderdale, FL 33314",NaN,NaN,Full-time,In-office,Business Systems/Data Analyst III - 991491 Job...,Education,Fort Lauderdale,FL
1450,"Analyst, Health Informatics Principal",California State University,3.7,"Bloomington, MN",NaN,NaN,Full-time,In-office,JOB DESCRIPTION HealthPartners is hiring a Hea...,Education,Bloomington,MN
1451,Hispanic Serving Institution (HSI) Data Analyst,Clario,4.0,"Redlands, CA 92374","$66,560 - $72,500 a year",69530.0,Full-time,In-office,POSITION CODE: 6952 DEPARTMENT/ADMINISTRATION:...,Software Development,Redlands,CA
1452,Business Analyst,Coterie Insurance,3.2,"Charlotte, NC",NaN,NaN,Full-time,In-office,Job Description: Role Summary: The Business An...,Insurance,Charlotte,NC

In [49]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1453 entries, 0 to 1452
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            1453 non-null   object
 1   employer             1453 non-null   object
 2   rating               1271 non-null   float64
 3   location             1453 non-null   object
 4   salary_raw           834 non-null    object
 5   salary_annual        834 non-null    float64
 6   job_type             1099 non-null   object
 7   work_mode            1453 non-null   object
 8   raw_job_description  1453 non-null   object
 9   job_description      1453 non-null   object
 10  industry             789 non-null    object
 11  city                 1262 non-null   object
 12  state                1320 non-null   object
dtypes: float64(2), object(11)
memory usage: 147.7+ KB

In [50]:
df_clean.isnull().sum()

job_title                0
employer                 0
rating                 182
location                 0
salary_raw             619
salary_annual          619
job_type               354
work_mode                0
raw_job_description      0
job_description          0
industry               664
city                   191
state                  133
dtype: int64

In [51]:
x=['industry','city','state']
for i in x:
    df_clean[i]=df_clean[i].fillna("Not Specified")

In [52]:
df_clean.isnull().sum()

job_title                0
employer                 0
rating                 182
location                 0
salary_raw             619
salary_annual          619
job_type               354
work_mode                0
raw_job_description      0
job_description          0
industry                 0
city                     0
state                    0
dtype: int64

In [53]:
y=df_clean['job_type']
y.value_counts()

job_type
Full-time               1002
Contract                  52
Full-time Contract        11
Part-time                  9
Part-time Full-time        6
Temp-to-hire               3
Part-time Contract         2
Internship                 2
Seasonal                   2
Per diem                   2
Temporary Contract         2
Full-time Temporary        1
Full-time Permanent        1
Temporary                  1
Full-time Internship       1
PRN                        1
Permanent Full-time        1
Name: count, dtype: int64

In [ ]:
y.isnull().sum()

np.int64(354)

In [61]:
def job_clean(x):
    if pd.isnull(x):
        return 'Not Specified'
    x=x.lower()
    if "intern" in x:
        return "Internship"
    elif "contract" in x or "temp" in x:
        return "Contract/Temp"
    elif "part-time" in x:
        return "Part-time"
    elif "full-time" in x or "permanent" in x:
        return "Full-time"
    else:
        return "Other"
df_clean['job_type_clean']=df_clean['job_type'].apply(job_clean)
df_clean['job_type_clean'].value_counts()

job_type_clean
Full-time        1004
Not Specified     354
Contract/Temp      72
Part-time          15
Other               5
Internship          3
Name: count, dtype: int64

In [70]:
df_clean['job_title'].isnull().sum()

np.int64(0)

In [69]:
df_clean['job_title'].value_counts()

job_title
Data Analyst                                89
Business Analyst                            83
Senior Data Analyst                         30
Business Intelligence Analyst               24
IT Business Analyst                         12
                                            ..
Senior Tracking Data Fusion Analyst          1
Data Privacy Lead Analyst - C13 (Hybrid)     1
Technical/Scientific Data Analyst            1
Criminal Intelligence Analyst (Vacancy)      1
Data Analyst 1                               1
Name: count, Length: 1061, dtype: int64

In [86]:
def job_title_clean(x):
    if pd.isnull(x):
        return 'Not Specified'
    x=x.lower()
    if ('sr.' in x or 'sr ' in x or 'senior' in x) and 'data' in x:
        return 'Senior Data Analyst'
    elif 'business' in x and 'intelligence' in x:
        return 'BI Analyst'
    elif 'data' in x:
        return 'Data Analyst'
    elif 'business' in x:
        return 'Business Analyst'
    else:
        return 'Others'

df_clean['job_title_cleaned']=df_clean['job_title'].apply(job_title_clean)
df_clean['job_title_cleaned'].value_counts()

job_title_cleaned
Data Analyst           709
Business Analyst       279
Senior Data Analyst    207
Others                 200
BI Analyst              58
Name: count, dtype: int64

In [77]:
df_clean['job_title'].tail(50)

1403                          Global ITSM Process Analyst
1404                        Business Intelligence Analyst
1405                                      BILLING ANALYST
1406                                 Data Analyst III ICP
1407                                     Analyst HSE Data
1408      Data Analyst (U.S. Customs & Border Protection)
1409    Revenue Analyst II, SMGS Ops - Data Products &...
1410    Business Analyst/Scrum Master – Contract Position
1411              Associate Business Intelligence Analyst
1412                               DATA STANDARDS ANALYST
1413                           Portfolio Business Analyst
1414                                     Business Analyst
1415                            Data Analytics Specialist
1416                      Financial Recovery Data Analyst
1417                            Data Analytics Specialist
1418            UW MEDICINE FOUNDATION DATA MODEL ANALYST
1419                                         FP&A Analyst
1420    Single Family Business Analyst (Hybrid- 3 Days...
1421           Sr. Analyst – New Store Delivery Analytics
1422       INSIGHTS ANALYST II, FCH - WORKFORCE ANALYTICS
1423    Repair Operations Center (ROC) Analyst, AppleC...
1424                Fraud Strategy & Analytics Analyst II
1425              Services Senior Operations Data Analyst
1426                                     Business Analyst
1427                              Senior Business Analyst
1428                  Senior Tracking Data Fusion Analyst
1429             Data Privacy Lead Analyst - C13 (Hybrid)
1430                    Technical/Scientific Data Analyst
1431              Criminal Intelligence Analyst (Vacancy)
1432    GPS HST Contractor Conversion Project Delivery...
1433                                     Research Analyst
1434          IT Analyst, Staff Specialist - BI Developer
1435           Data Standard Analyst - Biostatistics Team
1436                       Master Data Analyst - Item Add
1437                                     Business Analyst
1438                   IAS First Line Risk Senior Analyst
1439           Technology Business Analyst - Limited Term
1440              Client Account Maintenance Data Analyst
1441    Hydrogen Business Analyst I - Hydrogen Solutio...
1442            Analyst, Data Surveillance & Epidemiology
1443             Senior Data Information Services Analyst
1444                           Tactical Data Link Analyst
1445    Pharmacy Data Intelligence Analyst Central Pha...
1446                                Business Data Analyst
1447                            ADP HRIS Business Analyst
1448               ASSOCIATE GOVERNMENTAL PROGRAM ANALYST
1449                    Business Systems/Data Analyst III
1450                Analyst, Health Informatics Principal
1451      Hispanic Serving Institution (HSI) Data Analyst
1452                                     Business Analyst
Name: job_title, dtype: object

In [87]:
df_clean.to_csv("../data/indeed_clean.csv", index=False)

In [ ]:
check = pd.read_csv("../data/indeed_clean.csv")
print(check.shape)
print(check.columns.tolist())
check.head()

(1453, 15)
['job_title', 'employer', 'rating', 'location', 'salary_raw', 'salary_annual', 'job_type', 'work_mode', 'raw_job_description', 'job_description', 'industry', 'city', 'state', 'job_type_clean', 'job_title_cleaned']

,job_title,employer,rating,location,salary_raw,salary_annual,job_type,work_mode,raw_job_description,job_description,industry,city,state,job_type_clean,job_title_cleaned
0,Data Analyst,NYU Langone Health,4.3,"240 E 38 St, New York, NY 10016","$62,400 - $65,000 a year",63700.0,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",NYU Grossman School of Medicine is one of the ...,Healthcare,New York,NY,Full-time,Data Analyst
1,Data Analyst 1,"Human Rights, Division of",NaN,"Albany, NY 12220","$65,001 - $82,656 a year",73828.5,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",Minimum Qualifications Bachelor’s degree in da...,NaN,Albany,NY,Full-time,Data Analyst
2,Claims Data Analyst,Healthfirst,3.3,Remote,"$59,800 - $97,815 a year",78807.5,Full-time,Remote,"<div class=""jobsearch-JobComponent-description...",This position is Remote Develop and maintain n...,NaN,NaN,NaN,Full-time,Data Analyst
3,HRIS Data Analyst,Hershey Entertainment & Resorts Company,3.8,"27 W Chocolate Ave, Hershey, PA 17033",NaN,NaN,Full-time,In-office,"<div class=""jobsearch-JobComponent-description...",Hershey Entertainment & Resorts Company (HE&R)...,NaN,Hershey,PA,Full-time,Data Analyst
4,Artist Engagement Data Analyst - USDS,TikTok,3.4,"Los Angeles, CA","$82,227 - $168,355 a year",125291.0,NaN,Hybrid work,"<div class=""jobsearch-JobComponent-description...",Responsibilities About TikTok U.S. Data Securi...,Internet & Web Services,Los Angeles,CA,Not Specified,Data Analyst